#!/bin/bash
#SBATCH --job-name=arg_train
#SBATCH --output=logs/train_%A_%a.out
#SBATCH --error=logs/train_%A_%a.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=32G
#SBATCH --gres=gpu:1
#SBATCH --array=0-5          # 0=gsm8k 1=aqua 2=multiarith 3=svamp 4=humaneval 5=mmlu
#SBATCH -p gpu
#SBATCH --time=2-00:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=poomphob.suwannapichat@uni.lu

# ---------------------------------------------------------------------------
# Train ARGDesigner on cold-start data generated by cold_start_all.sh.
#
# Array index → dataset:
#   0  gsm8k
#   1  aqua
#   2  multiarith
#   3  svamp
#   4  humaneval
#   5  mmlu
#
# Required env var:
#   (none — defaults assume cold_start_all.sh output dirs)
#
# Optional overrides:
#   COLD_START_ROOT   root prefix for cold-start dirs   (default: ColdStartData_hf)
#   CHECKPOINT_ROOT   root prefix for checkpoint dirs   (default: checkpoints)
#   EPOCHS            training epochs                    (default: 100)
#   BATCH_SIZE        training batch size                (default: 32)
#   LR                learning rate                      (default: 1e-4)
#   VAL_RATIO         validation split fraction          (default: 0.1)
#
# Usage:
#   sbatch slurm/train.sh
#   sbatch --array=0 slurm/train.sh          # gsm8k only
#   EPOCHS=200 sbatch slurm/train.sh
# ---------------------------------------------------------------------------

set -euo pipefail

# Load CUDA modules so libcudnn.so is on LD_LIBRARY_PATH before torch imports.
source "$(dirname "${BASH_SOURCE[0]}")/setup_cuda.sh"

DATASETS=(
    gsm8k       # 0
    aqua        # 1
    multiarith  # 2
    svamp       # 3
    humaneval   # 4
    mmlu        # 5
)
DATASET="${DATASETS[$SLURM_ARRAY_TASK_ID]}"

HF_MODEL="${HF_MODEL:-Qwen/Qwen3-8B}"
MODEL_SLUG="${HF_MODEL//\//-}"                     # Qwen/Qwen3-8B → Qwen-Qwen3-8B
COLD_START_ROOT="${COLD_START_ROOT:-ColdStartData}"
CHECKPOINT_ROOT="${CHECKPOINT_ROOT:-checkpoints}"
EPOCHS="${EPOCHS:-100}"
BATCH_SIZE="${BATCH_SIZE:-32}"
LR="${LR:-1e-4}"
VAL_RATIO="${VAL_RATIO:-0.1}"
SEED="${SEED:-42}"

DATA_DIR="${MODEL_SLUG}/${COLD_START_ROOT}/${DATASET}"
OUTPUT_DIR="${MODEL_SLUG}/${CHECKPOINT_ROOT}/${DATASET}"

PROJECT_ROOT="${SLURM_SUBMIT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
mkdir -p "$PROJECT_ROOT/logs"

echo "========================================"
echo "Job ID        : $SLURM_JOB_ID  (array task $SLURM_ARRAY_TASK_ID)"
echo "Node          : $SLURM_NODELIST"
echo "Dataset       : $DATASET"
echo "Cold-start dir: $DATA_DIR"
echo "Checkpoint dir: $OUTPUT_DIR"
echo "Epochs        : $EPOCHS  |  LR: $LR  |  Batch: $BATCH_SIZE"
echo "Started at    : $(date)"
echo "========================================"

cd "$PROJECT_ROOT"

uv run python experiment/pretrain.py \
    --dataset    "$DATASET" \
    --data_dir   "$DATA_DIR" \
    --output_dir "$OUTPUT_DIR" \
    --epochs     "$EPOCHS" \
    --lr         "$LR" \
    --batch_size "$BATCH_SIZE" \
    --val_ratio  "$VAL_RATIO" \
    --seed       "$SEED"

echo "========================================"
echo "Training complete for $DATASET"
echo "Model saved to: $OUTPUT_DIR"
echo "Finished at   : $(date)"
echo "========================================"
